/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/Index': RouteRecordInfo<'/auth/Index', '/auth/Index', Record<never, never>, Record<never, never>>,
    '/dashboard/Index': RouteRecordInfo<'/dashboard/Index', '/dashboard/Index', Record<never, never>, Record<never, never>>,
    '/Index': RouteRecordInfo<'/Index', '/Index', Record<never, never>, Record<never, never>>,
    '/Module': RouteRecordInfo<'/Module', '/Module', Record<never, never>, Record<never, never>>,
    '/password/Index': RouteRecordInfo<'/password/Index', '/password/Index', Record<never, never>, Record<never, never>>,
  }
}
